name: bdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - notebook
  - ipykernel
  - pandas
  - numpy
  - pyspark
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - requests
  - tqdm
  - pip:
      - findspark
